# Generated by Django 3.2 on 2022-11-15 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaruselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('image', models.ImageField(upload_to='media/carusel', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Karusel',
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
                ('phone_number', models.IntegerField(verbose_name='phone_number')),
                ('description', models.TextField(max_length=550, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Kontakt',
            },
        ),
        migrations.CreateModel(
            name='GallaryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('image', models.ImageField(upload_to='media/gallary', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Gallary Category',
            },
        ),
        migrations.CreateModel(
            name='OrderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Sub Order Category',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(blank=True, max_length=100, null=True)),
                ('servicename', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
            ],
            options={
                'verbose_name': 'Xona turlari',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='name')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
            ],
            options={
                'verbose_name': 'Xizmat kursatish turlari',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='key')),
                ('value', models.CharField(max_length=500, verbose_name='value')),
            ],
            options={
                'verbose_name': 'Sozlamalar',
            },
        ),
        migrations.CreateModel(
            name='SubServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('is_exist', models.BooleanField(default=True, verbose_name='is_exist')),
            ],
            options={
                'verbose_name': 'Sub Card Xizmatlar',
            },
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_one_room', to='clining.room')),
                ('service', models.ManyToManyField(blank=True, to='clining.Service')),
            ],
        ),
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
                ('phone_number', models.IntegerField(verbose_name='phone_number')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clining.ordercategory')),
            ],
            options={
                'verbose_name': 'Order Form',
            },
        ),
        migrations.CreateModel(
            name='GallaryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('gallary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clining.gallarycategory')),
            ],
            options={
                'verbose_name': 'Gallery Detail',
            },
        ),
        migrations.CreateModel(
            name='CaruselDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('carusel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clining.caruselimage')),
            ],
            options={
                'verbose_name': 'Carusel Detail',
            },
        ),
        migrations.CreateModel(
            name='CardServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('detail', models.TextField(verbose_name='detail')),
                ('service', models.ManyToManyField(to='clining.SubServices')),
            ],
            options={
                'verbose_name': 'Card Xizmatlar',
            },
        ),
    ]
