# Generated by Django 3.2 on 2022-11-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clining', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='roomprice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
