# Generated by Django 4.1.2 on 2022-11-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clining', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(blank=True, max_length=100, null=True, verbose_name='roomname')),
                ('roomprice', models.IntegerField(blank=True, null=True, verbose_name='roomprice')),
                ('servicename', models.CharField(blank=True, max_length=100, null=True, verbose_name='servicename')),
                ('user_namee', models.CharField(max_length=65, verbose_name='user name')),
                ('user_phone_number', models.CharField(max_length=65, verbose_name='user_phone_number')),
            ],
        ),
        migrations.CreateModel(
            name='RoomGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
            ],
            options={
                'verbose_name': 'Xona turlari Mehmonlar',
            },
        ),
        migrations.CreateModel(
            name='ServiceGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='name')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
            ],
            options={
                'verbose_name': 'Xizmat kursatish turlari Mehmonlar',
            },
        ),
    ]
