# Generated by Django 4.1.2 on 2022-11-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clining", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room", models.CharField(blank=True, max_length=100, null=True)),
                ("total", models.PositiveIntegerField()),
                ("service", models.ManyToManyField(blank=True, to="clining.service")),
            ],
        ),
    ]
