# Generated by Django 4.1.2 on 2022-11-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clining", "0002_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="room",
            new_name="roomname",
        ),
        migrations.AddField(
            model_name="order",
            name="roomprice",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
