# Generated by Django 4.1.2 on 2022-11-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clining', '0002_ordersguest_roomguest_serviceguest'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomguest',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='roomguest',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='roomguest',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='serviceguest',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='serviceguest',
            name='name_ru',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='serviceguest',
            name='name_uz',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='name'),
        ),
    ]
