# Generated by Django 3.2 on 2022-11-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clining', '0002_orders_roomprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='roomprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
