# Generated by Django 4.1.2 on 2022-11-21 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clining', '0003_roomguest_name_en_roomguest_name_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersguest',
            old_name='user_namee',
            new_name='user_name',
        ),
    ]
