# Generated by Django 3.2 on 2022-11-15 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clining', '0003_alter_orders_roomprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='totl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clining.total'),
        ),
    ]
