# Generated by Django 4.1.2 on 2022-11-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clining', '0003_alter_room2_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_name',
            field=models.CharField(default=0, max_length=65, verbose_name='user name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='user_phone_number',
            field=models.CharField(default=0, max_length=65, verbose_name='user_phone_number'),
            preserve_default=False,
        ),
    ]
