# Generated by Django 4.1.2 on 2022-11-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clining", "0003_rename_room_order_roomname_order_roomprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
