# Generated by Django 4.1.2 on 2022-11-21 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clining', '0004_orders_user_name_orders_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='phone_number',
        ),
    ]
