# Generated by Django 4.1.2 on 2022-11-21 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clining', '0005_remove_orders_name_remove_orders_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Xona datellari'},
        ),
    ]
