# Generated by Django 4.1.2 on 2022-11-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clining", "0005_alter_orderitem_room_alter_orderitem_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="service",
            field=models.ManyToManyField(blank=True, to="clining.service"),
        ),
    ]
